version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "daily"
      
  - package-ecosystem: "mix"
    directory: "/utilities/node_activator"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "mix"
    directory: "/utilities/spawn_co_elixir"
    schedule:
      interval: "daily"

  - package-ecosystem: "mix"
    directory: "/utilities/http_downloader"
    schedule:
      interval: "daily"

  - package-ecosystem: "mix"
    directory: "/benchmarks/onnx_to_axon_bench"
    schedule:
      interval: "daily"