include:
  - otp-version: "27.0"
    elixir-version: "1.15.8"
    working-directory: utilities/node_activator
  - otp-version: "27.0"
    elixir-version: "1.15.8"
    working-directory: utilities/spawn_co_elixir
  - otp-version: "27.0"
    elixir-version: "1.15.8"
    working-directory: utilities/http_downloader
  - otp-version: "27.0"
    elixir-version: "1.15.8"
    working-directory: benchmarks/distributed_computing_bench
  - otp-version: "27.0"
    elixir-version: "1.15.8"
    working-directory: benchmarks/onnx_to_axon_bench
  - otp-version: "27.0"
    elixir-version: "1.16.3"
    working-directory: utilities/node_activator
  - otp-version: "27.0"
    elixir-version: "1.16.3"
    working-directory: utilities/spawn_co_elixir
  - otp-version: "27.0"
    elixir-version: "1.16.3"
    working-directory: utilities/http_downloader
  - otp-version: "27.0"
    elixir-version: "1.16.3"
    working-directory: benchmarks/distributed_computing_bench
  - otp-version: "27.0"
    elixir-version: "1.16.3"
    working-directory: benchmarks/onnx_to_axon_bench
  - otp-version: "26.2.5"
    elixir-version: "1.15.8"
    working-directory: utilities/node_activator
  - otp-version: "26.2.5"
    elixir-version: "1.15.8"
    working-directory: utilities/spawn_co_elixir
  - otp-version: "26.2.5"
    elixir-version: "1.15.8"
    working-directory: utilities/http_downloader
  - otp-version: "26.2.5"
    elixir-version: "1.15.8"
    working-directory: benchmarks/distributed_computing_bench
  - otp-version: "26.2.5"
    elixir-version: "1.15.8"
    working-directory: benchmarks/onnx_to_axon_bench
  - otp-version: "26.2.5"
    elixir-version: "1.16.3"
    working-directory: utilities/node_activator
  - otp-version: "26.2.5"
    elixir-version: "1.16.3"
    working-directory: utilities/spawn_co_elixir
  - otp-version: "26.2.5"
    elixir-version: "1.16.3"
    working-directory: utilities/http_downloader
  - otp-version: "26.2.5"
    elixir-version: "1.16.3"
    working-directory: benchmarks/distributed_computing_bench
  - otp-version: "26.2.5"
    elixir-version: "1.16.3"
    working-directory: benchmarks/onnx_to_axon_bench