# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        working_directory: ["pelemay_backend"]
        os: [ubuntu-20.04, windows-2022]
    defaults:
      run:
        working-directory: ${{ matrix.working_directory }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.4' # Define the elixir version [required]
        otp-version: '24.0' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/${{ matrix.working_directory }}/deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}/{1}/mix.lock', github.workspace, matrix.working_directory)) }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile and check warning
      run: mix compile --warnings-as-errors
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run tests
      run: mix test
