# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths-ignore:
      - '*.md'
      - '**/*.md'
      - '*.cff'
      - 'LICENSE*'
      - '**/LICENSE*'
      - 'config/*'
      - 'lib/**/*'
      - 'priv/**/*'
      - '.formatter.exs'
      - 'mix.{exs,lock}'
      - 'publish.exs'
      - '.github/workflows/nerves-build.yml'
      - '.github/workflows/site.yml'
  push:
    branches: [ "develop" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:

    name: Build and test on ${{ matrix.working-directory }}, ${{ matrix.os }}, ${{ matrix.elixir-version }}, ${{ matrix.otp-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        working-directory: ["utilities/backend_decorator", "utilities/node_activator", "backends/pelemay_backend", "backends/logging_backend", "benchmarks/onnx_to_axon_bench"]
        os: [ubuntu-20.04, ubuntu-22.04, windows-2022, macos-13, macos-12]
        otp-version: ['24.3.4.13', '25.3.2.3', '26.0.2']
        elixir-version: ['1.14.5', '1.15.2']
        exclude:
          - otp-version: '24.3.4.13'
            elixir-version: '1.15.2'
          - os: windows-2022
            otp-version: '25.3.2.3'
          - os: windows-2022
            otp-version: '26.0.2'
          - os: windows-2022
            elixir-version: '1.15.2'
          - os: macos-13
            otp-version: '24.3.4.13'
          - os: macos-12
            otp-version: '24.3.4.13'
          - os: macos-13
            otp-version: '26.0.2'
          - os: macos-12
            otp-version: '26.0.2'
          - os: macos-13
            elixir-version: '1.15.2'
          - os: macos-12
            elixir-version: '1.15.2'
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
    - uses: actions/checkout@v3
    - uses: kenchan0130/actions-system-info@master
      id: system-info
    - name: Set up OTP MAJOR and MINOR VERSION
      run: |
        echo "OTP_MAJOR_VERSION=$(echo ${{ matrix.otp-version }} | sed -e 's/^\([^\.]*\)\.\(.*\)$/\1/')" >> $GITHUB_ENV
        echo "OTP_MINOR_VERSION=$(echo ${{ matrix.otp-version }} | sed -e 's/^\([^\.]*\)\.\([^\.]*\).*$/\2/')" >> $GITHUB_ENV
    - name: Set versions Elixir and OTP
      run: |
        echo "erlang ${{ matrix.otp-version }}" >> ${{ github.workspace }}/.tool-versions
        echo "elixir ${{ matrix.elixir-version }}-otp-${{ env.OTP_MAJOR_VERSION }}" >> ${{ github.workspace }}/.tool-versions
    - name: Set up Elixir
      continue-on-error: true
      id: set_up_elixir_by_setup-beam
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
    - name: Install asdf
      continue-on-error: true
      if: ${{ steps.set_up_elixir_by_setup-beam.outcome == 'failure' }}
      id: install_asdf
      uses: asdf-vm/actions/setup@v2
    - name: Restore .asdf
      if: ${{ steps.install_asdf.outcome == 'success' }}
      id: asdf-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.asdf/
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-asdf-${{ hashFiles('**/.tool-versions') }}
        restore-keys: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-asdf-
    - name: Set up Elixir by asdf (Ubuntu)
      if: ${{ steps.asdf-cache.outcome == 'success' && steps.asdf-cache.outputs.cache-hit != 'true' && startsWith(runner.os, 'linux') }}
      uses: asdf-vm/actions/install@v2.1.0
      with:
        before_install: |
          sudo apt -y install build-essential automake autoconf git squashfs-tools ssh-askpass pkg-config curl libmnl-dev
    - name: Set up Elixir by asdf (macOS)
      if: ${{ steps.asdf-cache.outcome == 'success' && steps.asdf-cache.outputs.cache-hit != 'true' && startsWith(runner.os, 'macos') }}
      uses: asdf-vm/actions/install@v2.1.0
      with:
        before_install: |
          brew install wxwidgets openjdk fop openssl@3
          export CC="/usr/bin/gcc -I$(brew --prefix unixodbc)/include"
          export LDFLAGS="-L$(brew --prefix unixodbc)/lib"
          echo 'setup CC and LDFLAGS'
          if [ ${{ env.OTP_MAJOR_VERSION }} -eq 25 ]; then 
            if [ ${{ env.OTP_MINOR_VERSION }} -ge 1 ]; then
              export KERL_CONFIGURE_OPTIONS="--with-ssl=$(brew --prefix openssl@3) --with-odbc=$(brew --prefix unixodbc)"
            else
              export KERL_CONFIGURE_OPTIONS="--with-ssl=$(brew --prefix openssl@1.1) --with-odbc=$(brew --prefix unixodbc)"
            fi
          elif [ ${{ env.OTP_MAJOR_VERSION }} -ge 26 ]; then
            export KERL_CONFIGURE_OPTIONS="--with-ssl=$(brew --prefix openssl@3) --with-odbc=$(brew --prefix unixodbc)"
          else
            export KERL_CONFIGURE_OPTIONS="--with-ssl=$(brew --prefix openssl@1.1) --with-odbc=$(brew --prefix unixodbc)"
          fi
          echo "KERL_CONFIGURE_OPTIONS=$KERL_CONFIGURE_OPTIONS"
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/${{ matrix.working-directory }}/deps
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-Elixir-${{ matrix.elixir-version }}-OTP-${{ matrix.otp-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-Elixir-${{ matrix.elixir-version }}-OTP-${{ matrix.otp-version }}-
    - name: Set up hex and rebar (macOS)
      if: ${{ steps.set_up_elixir_by_setup-beam.outcome == 'failure' }}
      run: | 
        mix local.hex --force
        mix local.rebar --force
    - name: Install dependencies
      run: mix deps.get
    - name: Compile and check warning
      run: mix compile --warnings-as-errors
    - name: Check formatting (Ubuntu, macOS)
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: mix format --check-formatted
    - name: Check by credo (Ubuntu)
      if: ${{ startsWith(runner.os, 'linux') }}
      run: mix credo
    - name: Restore dialyzer cache (Ubuntu)
      if: ${{ startsWith(runner.os, 'linux') }}
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/${{ matrix.working-directory }}/_build/dev/dialyxir_erlang-${{ matrix.otp-version }}_elixir-${{ matrix.elixir-version }}_deps-dev.plt*
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-Elixir-${{ matrix.elixir-version }}-OTP-${{ matrix.otp-version }}-repo-${{ matrix.working-directory }}-plt
        restore-keys: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-Elixir-${{ matrix.elixir-version }}-OTP-${{ matrix.otp-version }}-repo-${{ matrix.working-directory }}-plt
    - name: Check by dialyzer (Ubuntu)
      if: ${{ startsWith(runner.os, 'linux') }}
      run: mix dialyzer
    - name: Run tests
      run: mix test
