# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (DistributedComputingBench)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths:
      - 'benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_distributed_computing_bench.yml'
      - '.github/workflows/reusable_ci.yml'
      - '.github/actions/matrix_check.yml'
      - '.github/actions/matrix_test.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
  push:
    branches: [ "main", "develop" ]    
    paths:
      - 'benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_distributed_computing_bench.yml'
      - '.github/workflows/reusable_ci.yml'
      - '.github/actions/matrix_check.yml'
      - '.github/actions/matrix_test.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  constants:
    name: Constants
    runs-on: ubuntu-latest
    outputs:
      matrix-for-check: ${{ steps.set-matrix-for-check.outputs.matrix }}
      matrix-test: ${{ steps.set-matrix-test.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix-for-check
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_check.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(STDIN))' | jq -c)
          echo "matrix=${json}" >> $GITHUB_OUTPUT
      - id: set-matrix-test
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_test.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(STDIN))' | jq -c)
          echo "matrix=${json}" >> $GITHUB_OUTPUT
  check_distributed_computing_bench:
    name: Check DistributedComputingBench
    needs: constants
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-for-check }}
      perform-check: true
  test_ubuntu_22_distributed_computing_bench:
    name: Test DistributedComputingBench (Ubuntu 22.04)
    needs: [constants, check_distributed_computing_bench]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
  test_ubuntu_20_distributed_computing_bench:
    name: Test DistributedComputingBench (Ubuntu 22.04)
    needs: [constants, check_distributed_computing_bench]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: ubuntu-20.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
  test_macos_13_distributed_computing_bench:
    name: Test DistributedComputingBench (macOS 13)
    needs: [constants, test_ubuntu_22_distributed_computing_bench, test_ubuntu_20_distributed_computing_bench]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: macos-13
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
  test_macos_12_distributed_computing_bench:
    name: Test DistributedComputingBench (macOS 12)
    needs: [constants, test_ubuntu_22_distributed_computing_bench, test_ubuntu_20_distributed_computing_bench]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: macos-12
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
