# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (HttpDownloader)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths:
      - 'utilities/http_downloader/**'
      - '!benchmarks/onnx_to_axon_bench/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_http_downloader.yml'
      - '.github/actions/reusable_ci.yml'
      - '.github/actions/matrix_check.yml'
      - '.github/actions/matrix_test.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
  push:
    branches: [ "main", "develop" ]    
    paths:
      - 'utilities/http_downloader/**'
      - '!benchmarks/onnx_to_axon_bench/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_http_downloader.yml'
      - '.github/actions/reusable_ci.yml'
      - '.github/actions/matrix_check.yml'
      - '.github/actions/matrix_test.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  constants:
    name: Constants
    runs-on: ubuntu-latest
    outputs:
      matrix-for-check: ${{ steps.set-matrix-for-check.outputs.matrix }}
      matrix-test: ${{ steps.set-matrix-test.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix-for-check
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_check.yml| ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
      - id: set-matrix-test
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_test.yml | ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
  check_http_downloader:
    name: Check HttpDownloader
    needs: constants
    uses: ./.github/actions/reusable_ci.yml
    with:
      working-directory: utilities/http_downloader
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-for-check }}
      perform-check: true
  test_ubuntu_22_http_downloader:
    name: Test HttpDownloader (Ubuntu 22.04)
    needs: [constants, check_http_downloader]
    uses: ./.github/actions/reusable_ci.yml
    with:
      working-directory: utilities/http_downloader
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
  test_ubuntu_20_http_downloader:
    name: Test HttpDownloader (Ubuntu 20.04)
    needs: [constants, check_http_downloader]
    uses: ./.github/actions/reusable_ci.yml
    with:
      working-directory: utilities/http_downloader
      os: ubuntu-20.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
