# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (HttpDownloader)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths:
      - 'utilities/http_downloader/**'
      - '!benchmarks/onnx_to_axon_bench/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_http_downloader.yml'
      - '.github/workflows/reusable_elixir_ci.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
  push:
    branches: [ "main", "develop" ]    
    paths:
      - 'utilities/http_downloader/**'
      - '!benchmarks/onnx_to_axon_bench/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_http_downloader.yml'
      - '.github/workflows/reusable_elixir_ci.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  elixir_ci_http_downloader:
    uses: ./.github/workflows/reusable_elixir_ci.yml
    with:
      working-directory: utilities/http_downloader
  elixir_ci_onnx_to_axon_bench:
    uses: ./.github/workflows/reusable_elixir_ci.yml
    needs: elixir_ci_http_downloader
    with:
      working-directory: benchmarks/onnx_to_axon_bench
  elixir_ci_distributed_computing_bench:
    uses: ./.github/workflows/reusable_elixir_ci.yml
    needs: elixir_ci_http_downloader
    with:
      working-directory: benchmarks/distributed_computing_bench
        