# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (NodeActivator)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths:
      - 'utilities/node_activator/**'
      - '!utilities/spawn_co_elixir/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_node_activator.yml'
      - '.github/workflows/reusable_ci.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
  push:
    branches: [ "main", "develop" ]    
    paths:
      - 'utilities/node_activator/**'
      - '!utilities/spawn_co_elixir/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_node_activator.yml'
      - '.github/workflows/reusable_ci.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  elixir_ci_node_activator_ubuntu:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        otp-version: ['24.3.4.13', '25.3.2.3', '26.0.2']
        elixir-version: ['1.14.5', '1.15.4']
        exclude:
          - otp-version: '24.3.4.13'
            elixir-version: '1.15.4'
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: utilities/node_activator
      os: ${{ matrix.os }}
      otp-version: ${{ matrix.otp-version }}
      elixir-version: ${{ matrix.elixir-version }}
  elixir_ci_spawn_co_elixir_ubuntu:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        otp-version: ['24.3.4.13', '25.3.2.3', '26.0.2']
        elixir-version: ['1.14.5', '1.15.4']
        exclude:
          - otp-version: '24.3.4.13'
            elixir-version: '1.15.4'
    uses: ./.github/workflows/reusable_ci.yml
    needs: elixir_ci_node_activator_ubuntu
    with:
      working-directory: utilities/spawn_co_elixir
      os: ${{ matrix.os }}
      otp-version: ${{ matrix.otp-version }}
      elixir-version: ${{ matrix.elixir-version }}
  elixir_ci_distributed_computing_bench_ubuntu:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        otp-version: ['24.3.4.13', '25.3.2.3', '26.0.2']
        elixir-version: ['1.14.5', '1.15.4']
        exclude:
          - otp-version: '24.3.4.13'
            elixir-version: '1.15.4'
    uses: ./.github/workflows/reusable_ci.yml
    needs: elixir_ci_spawn_co_elixir_ubuntu
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: ${{ matrix.os }}
      otp-version: ${{ matrix.otp-version }}
      elixir-version: ${{ matrix.elixir-version }}
  elixir_ci_node_activator_other:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-13, macos-12]
        # os: [windows-2022, macos-13, macos-12]
        otp-version: ['24.3.4.13']
        elixir-version: ['1.14.5']
    uses: ./.github/workflows/reusable_ci.yml
    needs: elixir_ci_node_activator_ubuntu
    with:
      working-directory: utilities/node_activator
      os: ${{ matrix.os }}
      otp-version: ${{ matrix.otp-version }}
      elixir-version: ${{ matrix.elixir-version }}
  elixir_ci_spawn_co_elixir_other:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-13, macos-12]
        # os: [windows-2022, macos-13, macos-12]
        otp-version: ['24.3.4.13']
        elixir-version: ['1.14.5']
    uses: ./.github/workflows/reusable_ci.yml
    needs: elixir_ci_spawn_co_elixir_ubuntu
    with:
      working-directory: utilities/spawn_co_elixir
      os: ${{ matrix.os }}
      otp-version: ${{ matrix.otp-version }}
      elixir-version: ${{ matrix.elixir-version }}
  elixir_ci_distributed_computing_bench_other:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-13, macos-12]
        # os: [windows-2022, macos-13, macos-12]
        otp-version: ['24.3.4.13']
        elixir-version: ['1.14.5']
    uses: ./.github/workflows/reusable_ci.yml
    needs: elixir_ci_distributed_computing_bench_ubuntu
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: ${{ matrix.os }}
      otp-version: ${{ matrix.otp-version }}
      elixir-version: ${{ matrix.elixir-version }}
