# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (NodeActivator)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop", "check_by_SHR" ]
    paths:
      - 'utilities/node_activator/**'
      - '!utilities/spawn_co_elixir/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_node_activator.yml'
      - '.github/workflows/reusable_ci.yml'
      - '.github/actions/matrix_check.yml'
      - '.github/actions/matrix_test.yml'
      - '.github/actions/matrix_reduced_test_1.yml'
      - '.github/actions/matrix_reduced_test_2.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
  push:
    branches: [ "main", "develop", "check_by_SHR" ]
    paths:
      - 'utilities/node_activator/**'
      - '!utilities/spawn_co_elixir/**'
      - '!benchmarks/distributed_computing_bench/**'
      - '!.github/workflows/*'
      - '.github/workflows/ci_node_activator.yml'
      - '.github/workflows/reusable_ci.yml'
      - '.github/actions/matrix_check.yml'
      - '.github/actions/matrix_test.yml'
      - '.github/actions/matrix_reduced_test_1.yml'
      - '.github/actions/matrix_reduced_test_2.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  constants:
    name: Constants
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-22.04
    outputs:
      matrix-for-check: ${{ steps.set-matrix-for-check.outputs.matrix }}
      matrix-test: ${{ steps.set-matrix-test.outputs.matrix }}
      matrix-reduced-test-1: ${{ steps.set-matrix-reduced-test-1.outputs.matrix }}
      matrix-reduced-test-2: ${{ steps.set-matrix-reduced-test-2.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix-for-check
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_check.yml| ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
      - id: set-matrix-test
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_test.yml | ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
      - id: set-matrix-reduced-test-1
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_reduced_test_1.yml | ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
      - id: set-matrix-reduced-test-2
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_reduced_test_2.yml | ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
  check_node_activator:
    name: Check NodeActivator
    needs: constants
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: utilities/node_activator
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-for-check }}
      perform-check: true
  test_ubuntu_22_node_activator:
    name: Test NodeActivator (Ubuntu 22.04)
    needs: [constants, check_node_activator]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: utilities/node_activator
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
  test_ubuntu_22_spawn_co_elixir:
    name: Test SpawnCoElixir (Ubuntu 22.04)
    needs: [constants, test_ubuntu_22_node_activator]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: utilities/spawn_co_elixir
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
  test_ubuntu_22_distribued_computing_bench:
    name: Test DistributedComputingBench (Ubuntu 22.04)
    needs: [constants, test_ubuntu_22_node_activator]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: benchmarks/distributed_computing_bench
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
