# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (OnnxToAxonBench)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths:
      - '!*.md'
      - '!**/*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!**/LICENSE*'
      - '!publish.exs'
      - '!.github/workflows/*'
      - '.github/workflows/ci_onnx_to_axon_bench.yml'
      - 'benchmarks/onnx_to_axon_bench/*'
  push:
    branches: [ "develop" ]    
    paths:
      - '!*.md'
      - '!**/*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!**/LICENSE*'
      - '!publish.exs'
      - '!.github/workflows/*'
      - '.github/workflows/ci_onnx_to_axon_bench.yml'
      - 'benchmarks/onnx_to_axon_bench/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  elixir_ci_onnx_to_axon_bench:
    uses: ./.github/workflows/reusable_elixir_ci.yml
    with:
      working-directory: benchmarks/onnx_to_axon_bench
