# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI

name: Elixir CI (PelemayBackend)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["develop", "check_by_SHR"]
    paths:
      - "backends/pelemay_backend/**"
      - "!benchmarks/onnx_to_axon_bench/**"
      - "!benchmarks/distributed_computing_bench/**"
      - "!.github/workflows/*"
      - ".github/workflows/ci_pelemay_backend.yml"
      - ".github/workflows/reusable_ci.yml"
      - ".github/actions/matrix_check.yml"
      - ".github/actions/matrix_test.yml"
      - "!**/*.md"
      - "!**/LICENSE*"
      - "!*.md"
      - "!*.cff"
      - "!LICENSE*"
      - "!publish.exs"
  push:
    branches: ["main", "develop", "check_by_SHR"]
    paths:
      - "utilities/http_downloader/**"
      - "!benchmarks/onnx_to_axon_bench/**"
      - "!benchmarks/distributed_computing_bench/**"
      - "!.github/workflows/*"
      - ".github/workflows/ci_http_downloader.yml"
      - ".github/workflows/reusable_ci.yml"
      - ".github/actions/matrix_check.yml"
      - ".github/actions/matrix_test.yml"
      - "!**/*.md"
      - "!**/LICENSE*"
      - "!*.md"
      - "!*.cff"
      - "!LICENSE*"
      - "!publish.exs"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  constants:
    name: Constants
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-22.04
    outputs:
      matrix-for-check: ${{ steps.set-matrix-for-check.outputs.matrix }}
      matrix-test: ${{ steps.set-matrix-test.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix-for-check
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_check.yml| ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
      - id: set-matrix-test
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_test.yml | ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
  check_pelemay_backend:
    name: Check PelemayBackend
    needs: constants
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: backends/pelemay_backend
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-for-check }}
      perform-check: true
  test_ubuntu_22_pelemay_backend:
    name: Test PelemayBackend (Ubuntu 22.04)
    needs: [constants, check_pelemay_backend]
    uses: ./.github/workflows/reusable_ci.yml
    with:
      working-directory: backends/pelemay_backend
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-test }}
      perform-check: false
