# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# CI 

name: Elixir CI (SpawnCoElixir)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "develop" ]
    paths:
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
      - '!.github/workflows/*'
      - '.github/workflows/ci_spawn_co_elixir.yml'
      - 'utilities/spawn_co_elixir/*'
      - '!**/*.md'
      - '!**/LICENSE*'
  push:
    branches: [ "main", "develop" ]    
    paths:
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'
      - '!.github/workflows/*'
      - '.github/workflows/ci_spawn_co_elixir.yml'
      - 'utilities/spawn_co_elixir/*'
      - '!**/*.md'
      - '!**/LICENSE*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  elixir_ci_spawn_co_elixir:
    uses: ./.github/workflows/reusable_elixir_ci.yml
    with:
      working-directory: utilities/spawn_co_elixir
