name: Self-hosted CI on macOS

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  constants:
    name: Constants
    if: startsWith(github.head_ref, 'check_by_SHR')
    runs-on: ubuntu-latest
    outputs:
      matrix-for-self-hosted-macos: ${{ steps.set-matrix-for-self-hosted-macos.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix-for-self-hosted-macos
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_for_self_hosted_macos.yml| ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
  test_self_hosted_matrix:
    name: Test Matrix (Selfhosted CI on macOS)
    needs: constants
    uses: ./.github/workflows/reusable_ci_for_self_hosted_runner_macos.yml
    with:
      matrix: ${{ needs.constants.outputs.matrix-for-self-hosted-macos }}
      perform-check: false
