name: Dependabot auto merge
on: 
  pull_request:
    paths:
      - '**/*'
      - '!.github/workflows/*'
      - '.github/workflows/dependabot_auto_merge.yml'
      - '.github/workflows/reusable_ci_with_working_directory.yml'
      - '.github/actions/matrix_dependabot.yml'
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!*.md'
      - '!*.cff'
      - '!LICENSE*'
      - '!publish.exs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: write
    pull-requests: write

jobs:
  constants:
    name: Constants
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    outputs:
      matrix-for-dependabot: ${{ steps.set-matrix-for-dependabot.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix-for-dependabot
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/matrix_dependabot.yml| ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT
  check_matrix:
    name: Check DistributedComputingBench
    needs: constants
    uses: ./.github/workflows/reusable_ci_with_working_directory.yml
    with:
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-for-dependabot }}
      perform-check: true
  test_ubuntu_22_matrix:
    name: Test DistributedComputingBench (Ubuntu 22.04)
    needs: [constants, check_matrix]
    uses: ./.github/workflows/reusable_ci_with_working_directory.yml
    with:
      os: ubuntu-22.04
      matrix: ${{ needs.constants.outputs.matrix-for-dependabot }}
      perform-check: false
  dependabot:
    runs-on: ubuntu-latest
    needs: [constants, check_matrix, test_ubuntu_22_matrix]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Change merge branch for Dependabot PR
        run: |
          gh pr edit "$PR_URL" --base 'check_by_SHR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve and enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr edit "$PR_URL" -t "(auto merged) $PR_TITLE"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}