name: Deploy Site

on:
    pull_request:
        branches: [ "main" ]
        paths-ignore:
        - '*.md'
        - '**/*.md'
        - '*.cff'
        - 'LICENSE*'
        - '**/LICENSE*'
        - 'backends/**/*'
        - 'utilitiles/**/*'
        - '.github/workflows/nerves-build.yml'
        - '.github/workflows/ci.yml'
    push:
      branches: [ "main" ]
  
jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Imagemagick (Ubuntu)
        run: apt -y install imagemagick

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.3.4.11'
          elixir-version: '1.14.4'

      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}

      - run: MIX_ENV=site mix deps.get

      - name: Install Imagemagick (Ubuntu)
        run: sudo apt -y install imagemagick

      - run: MIX_ENV=site mix still.compile

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site